import Head from "next/head";
import Footer from "../components/Footer";
import Form from "../components/Form";
import { Header } from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Twin</title>
        <meta name="description" content="Generated by Google" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Form />

      <Footer />
    </div>
  );
}
